config/routes.rb
Rails.application.routes.draw do

  resource :results, :only => [:show]

  resources :vote_cards

  resources :entries

  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best_in_show_vote.rb
class BestInShowVote < ApplicationRecord
  belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :best_in_show_votes, class_name: "VoteCard", inverse_of: :best_in_show, foreign_key: :best_in_show_id
  has_many :most_delicious_votes, class_name: "VoteCard", inverse_of: :most_delicious, foreign_key: :most_delicious_id
  has_many :most_decorative_votes, class_name: "VoteCard", inverse_of: :most_decorative, foreign_key: :most_decorative_id
  has_many :most_traditional_votes, class_name: "VoteCard", inverse_of: :most_traditional, foreign_key: :most_traditional_id
end

app/models/most_decorative_vote.rb
class MostDecorativeVote < ApplicationRecord
  belongs_to :entry
end

app/models/most_delicious_vote.rb
class MostDeliciousVote < ApplicationRecord
  belongs_to :entry
end

app/models/most_traditional_vote.rb
class MostTraditionalVote < ApplicationRecord
  belongs_to :entry
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/results.rb
class Results < ApplicationRecord
  def initialize(entries)
    @entries = entries
  end

  def best_in_show
    @entries.max_by do |entry|
      entry.best_in_show_votes.count
    end
  end

  def most_delicious
    @entries.max_by do |entry|
      entry.most_delicious_votes.count
    end
  end

  def most_decorative
    @entries.max_by do |entry|
      entry.most_decorative_votes.count
    end
  end
  
  def most_traditional
    @entries.max_by do |entry|
      entry.most_traditional_votes.count
    end
  end
end

app/models/vote_card.rb
class VoteCard < ApplicationRecord
  belongs_to :best_in_show, class_name: "Entry", inverse_of: :best_in_show_votes
  belongs_to :most_delicious, class_name: "Entry", inverse_of: :most_delicious_votes
  belongs_to :most_decorative, class_name: "Entry", inverse_of: :most_decorative_votes
  belongs_to :most_traditional, class_name: "Entry", inverse_of: :most_traditional_votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /entries/1
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:cookie, :baker)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def show
    @entries = Entry.all
    @results = Results.new(@entries)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/vote_cards_controller.rb
class VoteCardsController < ApplicationController
  before_action :set_vote_card, only: [:show, :edit, :update, :destroy]
  before_action :load_entries, only: [:new, :edit]

  # GET /vote_cards
  def index
    @vote_cards = VoteCard.all
  end

  # GET /vote_cards/1
  def show
  end

  # GET /vote_cards/new
  def new
    @vote_card = VoteCard.new
  end

  # GET /vote_cards/1/edit
  def edit
  end

  # POST /vote_cards
  def create
    @vote_card = VoteCard.new(vote_card_params)

    respond_to do |format|
      if @vote_card.save
        format.html { redirect_to @vote_card, notice: 'VoteCard was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /vote_cards/1
  def update
    respond_to do |format|
      if @vote_card.update(vote_card_params)
        format.html { redirect_to @vote_card, notice: 'VoteCard was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /vote_cards/1
  # DELETE /vote_cards/1.json
  def destroy
    @vote_card.destroy
    respond_to do |format|
      format.html { redirect_to vote_cards_url }
    end
  end

  private
    def set_vote_card
      @vote_card = VoteCard.find(params[:id])
    end

    def vote_card_params
      params.require(:vote_card).permit(:name, :best_in_show_id, :most_delicious_id, :most_decorative_id, :most_traditional_id)
    end
    def load_entries
      @entries = Entry.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vote_cards_helper.rb
module VoteCardsHelper
end

app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cookie %>
    <%= f.text_field :cookie %>
  </div>
<br/>
  <div class="field">
    <%= f.label :baker %>
    <%= f.text_field :baker %>
  </div>
<br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table id="table">
  <thead>
    <tr>
      <th>Cookie</th>
      <th>Baker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr id="row1">
        <td id="column1"><%= entry.cookie %></td>
        <td id="column1"><%= entry.baker %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<div >
  <h1>Enter Your Cookie</h1>

  <%= render 'form', entry: @entry %>
<br/>
  <%= link_to 'Back', entries_path %>
</div>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cookie:</strong>
  <%= @entry.cookie %>
</p>

<p>
  <strong>Baker:</strong>
  <%= @entry.baker %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookieparty</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <supports-screens
      android:smallScreens="false"
      android:normalScreens="false"
      android:largeScreens="true"
      android:xlargeScreens="true"
      android:requiresSmallestWidthDp="533"/>
  </head>
  <body>
      <div id = "cp_container">
        <div id="header_image">
          <%= link_to (image_tag("ludwig_family_cookie_party2017.png", :alt => "Ludwig Family Cookie Party", :width => '100%')), "/" %>
        </div> <!-- close header_image -->
        <div id="menu"><%= link_to 'VOTE', new_vote_card_path %> &nbsp; * &nbsp; <%= link_to 'ALL VOTES', vote_cards_path %> &nbsp; * &nbsp; <%= link_to 'ENTER A COOKIE', new_entry_path %> &nbsp; * &nbsp; <%= link_to 'ALL ENTRIES', entries_path %></div>
        <div id="blurb">
          <%= yield %> <!-- inserts view code here -->
        </div> <!-- blurb -->
    </div> <!-- cp_container -->
  </body>
</html>

app/views/results/show.html.erb
<h1> Results of the Cookie Party!</h1>
<p>
  <h2>Best in Show: </h2>
  <%= @results.best_in_show.cookie %>, <%= @results.best_in_show.best_in_show_votes.count %> Votes
</p>

<p>
  <h2>Most Delicious: </h2>
  <%= @results.most_delicious.cookie %>, <%= @results.most_delicious.most_delicious_votes.count %> Votes
</p>

<p>
  <h2>Most Creative: </h2>
  <%= @results.most_decorative.cookie %>, <%= @results.most_decorative.most_decorative_votes.count %> Votes
</p>

<p>
  <h2>Kids Choice: </h2>
  <%= @results.most_traditional.cookie %>, <%= @results.most_traditional.most_traditional_votes.count %> Votes
</p>

<%= link_to 'Back', "/" %>

app/views/static_pages/index.html.erb
<div style="text-align:center">
  <h2>&#10057; <%= link_to 'Enter a cookie to be voted on', new_entry_path %> &#10057;</h2>
  <h2>&#10057; <%= link_to 'Vote on your favorite cookies', new_vote_card_path %> &#10057;</h2>
  <h1 style="color: #396; font-size: 150%">Happy holidays &#10084; The Ludwig Family!</h1>
</div>

<!-- <div style="border:solid #555 1px; text-align:center">
  <h2>Winners 2015</h2>
  <p><b>Best in Show:</b>
  <br/>
  Peanutbutter Chocolatechip Gluten-Free Cookie</p>
  <p><b>Most Delicious:</b> Stefanie Swanson
  <br/>
  Meyer Lemon Vanilla-bean Cookie</p>
  <p><b>Most Decorative:</b> Erin Yasgar
  <br/>
  Schroder & Charlie Brown Cookie</p>
  <p><b>Most Traditional:</b> Charles
  <br/>
  Divinity</p>
</div>
 -->

app/views/vote_cards/_form.html.erb
<%= form_for(@vote_card) do |f| %>
  <% if @vote_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_card.errors.count, "error") %> prohibited this vote_card from being saved:</h2>

      <ul>
      <% @vote_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="voter"><%= f.label :name, "Your Name" %>&nbsp;
    <%= f.text_field :name %></div>
  </div>
  <br/>
  <h1>Your Votes</h1>
  <table>
    <tr>
      <td id="superlatives"">
        <div id="vote">&#9731; <%= f.label :best_in_show_id, "Best in Show" %></div>
      </td>
      <td id="superlatives">
        &#9731; <%= f.collection_select :best_in_show_id, @entries, :id, :cookie %>
      <td>
    </tr>
    <tr>
      <td id="superlatives">
        <div id="vote">&#10052; <%= f.label :most_delicious_id, "Most Delicious" %></div>
      </td>
      <td id="superlatives">
        &#10052; <%= f.collection_select :most_delicious_id, @entries, :id, :cookie %>
      <td>
    </tr>
    <tr>
      <td id="superlatives" style="width:250px;">
        <div id="vote"> &#9731; <%= f.label :most_decorative_id, "Most Creative" %></div>
      </td>
      <td id="superlatives" style="width:250px;">
        &#9731; <%= f.collection_select :most_decorative_id, @entries, :id, :cookie %>
      <td>
    </tr>
    <tr>
      <td id="superlatives" style="width:250px;">
        <div id="vote">&#10052; <%= f.label :most_traditional_id, "Kids Choice" %></div>
      </td>
      <td id="superlatives" style="width:250px;">
        &#10052; <%= f.collection_select :most_traditional_id, @entries, :id, :cookie %>
      <td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_cards/edit.html.erb
<h1>Edit your Vote Card</h1>

<%= render 'form', vote_card: @vote_card %>

<%= link_to 'Show', @vote_card %> |
<%= link_to 'Back', vote_cards_path %>

app/views/vote_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Voters</h2>
<table id="table">
  <tbody>
    <% @vote_cards.each do |vote_card| %>
    <tr id="row1">
      <td id="column1"><%= vote_card.name %></td>
      <td id="columncrud"><%= link_to 'Show', vote_card %></td>
      <td id="columncrud"><%= link_to 'Edit', edit_vote_card_path(vote_card) %></td>
      <td id="columncrud"><%= link_to 'Destroy', vote_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Vote Card', new_vote_card_path %>

app/views/vote_cards/new.html.erb
<h1>CAST YOUR VOTE</h1>
<ul id='voting_directions'>
  <li>Enter your name and then vote.</li>
  <li>When you are finished voting click on the "Create Vote Card" button to submit your vote.</li>
  <br/>
  <li>To Edit your vote click on the "ALL VOTES" button in the menu bar</li>
  <li>Find your name and click edit, then change your vote. </li>
  <li>Be sure to click "Update Vote Card" when you are finished.</li>
</ul>
<div style="border:solid 1px #666; padding:15px;">
  <%= render 'form' %>
</div>
<br/>
<%= link_to 'Back', "/" %>

app/views/vote_cards/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @vote_card.name %>'s Vote Card
</h1>

<p>
  <strong>Best in Show: </strong>
  <%= @vote_card.best_in_show.cookie %>
</p>

<p>
  <strong>Most Delicious: </strong>
  <%= @vote_card.most_delicious.cookie %>
</p>

<p>
  <strong>Most Creative: </strong>
  <%= @vote_card.most_decorative.cookie %>
</p>

<p>
  <strong>Kids Choice: </strong>
  <%= @vote_card.most_traditional.cookie %>
</p>

<%= link_to 'Edit', edit_vote_card_path(@vote_card) %> |
<%= link_to 'Back', vote_cards_path %>